### ISSUE TITLE
PUBLIC URL reference gets added twice in the CRA build, static resources fails to load

### ISSUE THREAD

**Issue by Dip686** [rossjrw/pr-preview-action#28] opened 2022-12-09 06:08 UTC
Website created using CRA. To build a feature branch running this command. `export PUBLIC_URL=pr-preview/pr-${{ github.event.number }} && npx react-scripts build`.
In the build file, `index.html` It is already adding pr-preview/pr-number before static resource path. But while loading, it is referring to the path twice (attached screenshot).
![Screenshot 2022-12-09 at 11 36 25 AM](https://user-images.githubusercontent.com/12895563/206635858-657a03a5-119c-4c70-a61d-7e6ffb3a072e.png)
![Screenshot 2022-12-09 at 11 36 50 AM](https://user-images.githubusercontent.com/12895563/206635920-5c99f724-cc44-4f40-b457-c9c7223248a6.png)
![Screenshot 2022-12-09 at 11 37 14 AM](https://user-images.githubusercontent.com/12895563/206635975-763e828d-6c28-43d3-9e44-27db1172bfb9.png)

**Comment by rossjrw** [comment] 2022-12-12 10:57
You are referencing your scripts with relative paths e.g.:

```
<script src="pr-preview/pr-8/static/script.js"></script>
```

A script src that doesn't start with a slash is relative to the current path: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#absolute_urls_vs_relative_urls

The current path is `/pr-preview/pr-8/`, so that would resolve to `/pr-preview/pr-8/pr-preview/pr-8/static/...`, as you experienced.

To access `https://<domain>/pr-preview/pr-8/static/script.js` from `/pr-preview/pr-8/`, your script src needs to be either `/pr-preview/pr-8/static/script.js` (with a leading slash to make it absolute with an implicit domain), or `static/script.js` (without a leading slash, to be relative to the current path).

I haven't used create-react-app or even React, so unfortunately I can't help you achieve that in that framework.

**Comment by rossjrw** [comment] 2022-12-12 10:59
Noting that I'm closing this issue as it's not a bug with this Action, but please feel free to respond and I'll help as best I can.

**Closed** 2022-12-12 10:59 UTC
Labels: question
