### ISSUE TITLE
Branch footer link in posted comment is wrong when a `deploy-repository` is used

### ISSUE THREAD

**Issue by vorburger** [rossjrw/pr-preview-action#66] opened 2023-11-02 05:14 UTC
E.g. in https://github.com/www-learn-study/saraswati.learn.study/pull/28 the https://www-learn-study.github.io/previews/pr-preview/pr-28/ URL is correct (there was a preview there, it's now removed again), but the https://github.com/www-learn-study/saraswati.learn.study/tree/gh-pages (from _on branch [gh-pages](https://github.com/www-learn-study/saraswati.learn.study/tree/gh-pages) at 2023-11-02 05:08 UTC_) is wrong... that should be https://github.com/www-learn-study/previews/tree/gh-pages - it's not using the `deploy-repository` there.

**Comment by rossjrw** [comment] 2023-11-02 20:14
Closing as duplicate of https://github.com/rossjrw/pr-preview-action/issues/50

**Closed by rossjrw** 2023-11-02 20:14 UTC
Labels: bug, duplicate
